### PR TITLE
fix windows hosts per line problem

### LINKED ISSUE #18: Multiple hosts per line added on Windows causes problems
I had users reporting that sites they were using would not load with 16 host entries on a line.

Further research indicates that Windows has an upper limit of 9 alias' per entry

#17 attempts to fix this

### PR DESCRIPTION
**Pull request by luthermonson**
closes #18

problem: windows has some limits to how many hosts it can have per line and we've seen more issues with 255 char dns limits
fix: rework flush to include a preFlushClean which targets windows/linux. linux is a noop but on windows we will force a 9 hosts per line limit. To accommodate this we have to add a `RemoveDuplicateIps` at the top of each HostsPerLine call to reset the internal hosts.Lines slice so that the 9/line limit is upheld. A developer who wants to override this can change the const HostsPerLine but use at your own risk on windows with values > 9

important: added a dns name validator which restricts > 255chars and has a regex to make sure weird special chars etc.

### CODE REVIEW

**Review by tomjn — APPROVED** [review]
Aside from the bundled `vendor` folder it looks fine here, though I'm not sure what the convention is re: committing dependencies in golang projects are

**Comment by luthermonson** [comment]
@tomjn we've been vendoring this whole time https://github.com/goodhosts/hostsfile/tree/master/vendor it's a typical thing to do especially with smaller project

**Comment by luthermonson** [comment]
tested with cli and i believe we can consider this issue resolved and we will merge this

```
~\goodhosts\cli [clean-flags] > gc hosts
127.0.0.2 host1 host2 host3 host4 host5 host6 host7 host8 host9 host10
~\goodhosts\cli [clean-flags] > goodhosts -f ./hosts add 127.0.0.3 test
hosts entry added: 127.0.0.3 test
~\goodhosts\cli [clean-flags] > gc hosts
127.0.0.2 host1 host2 host3 host4 host5 host6 host7 host8 host9
127.0.0.2 host10
127.0.0.3 test
```

**Comment by luthermonson** [comment]
validator working and this is the regex for reference `^([a-zA-Z0-9_]{1}[a-zA-Z0-9_-]{0,62}){1}(\.[a-zA-Z0-9_]{1}[a-zA-Z0-9_-]{0,62})*[\._]?$` just note that 63chars is the max up to the first `.` and 255 max chars is enforced now


```
~\goodhosts\cli [clean-flags] > goodhosts -f ./hosts add 127.0.0.3 *test
hostname is not a valid dns name: *test
~\goodhosts\cli [clean-flags] > goodhosts -f ./hosts add 127.0.0.3 "test asdf"
hostname is not a valid dns name: test asdf
```

**Pull request merged**
